In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Directory containing the Excel files
directory = '/Users/sarahsetiawan/Desktop/CSCAPSTONE/HOCKEYDATA/Instat_NEWDATA'

# List all files in the directory that start with "lines" and end with ".xlsx"
excel_files = [f for f in os.listdir(directory) if f.startswith('Lines') and f.endswith('.xlsx')]

# Combine all Excel files into a single DataFrame
lines_new_cleaned = pd.concat(
    [pd.read_excel(os.path.join(directory, file)) for file in excel_files],
    ignore_index=True
)

print(lines_new_cleaned)

                                                   Line Plus/Minus  \
0     4 K. MacKinnon, 18 A. Wilbur, 6 A. Wilson, 10 ...          -
1     15 D. Ormiston, 11 S. Potratz, 6 A. Wilson, 12...          -
2     26 J. Marano, 4 K. MacKinnon, 77 M. Cheesebrou...          -
3     15 D. Ormiston, 16 L. Scardicchio, 8 A. Bazyle...          -
4     15 D. Ormiston, 11 S. Potratz, 42 A. Reider, 6...          -
...                                                 ...        ...
1477  47 K. Kratzer, 12 E. Bynan, 77 M. Cheesebrough...          -
1478  47 K. Kratzer, 8 A. Bazylewicz, 12 E. Bynan, 7...          -
1479  47 K. Kratzer, 12 E. Bynan, 77 M. Cheesebrough...          -
1480  47 K. Kratzer, 18 A. Wilbur, 12 E. Bynan, 77 M...      -0.11
1481  47 K. Kratzer, 12 E. Bynan, 77 M. Cheesebrough...          -

      Numbers of shifts Time on ice Goals Opponent's goals Shots  \
0                   4.0       01:45     -                -     4
1                   1.0       00:43     -                -     4
2                   2.0       00:29     -                -     4
3                   2.0       00:47     -                -     3
4                   2.0       01:16     -                -     3
...                 ...         ...   ...              ...   ...
1477                1.0       00:15     -                -   0.5
1478                1.0       00:45     -                -     -
1479                1.0       00:11     -                -     -
1480                3.0       02:08  0.11             0.11   4.9
1481                1.0       00:23     -                -     -

     Shots on goal Opponent shots total Shots on goal against CORSI CORSI+  \
0                3                    -                     -     4      4
1                4                    -                     -     4      4
2                1                    -                     -     4      4
3                3                    -                     -     3      3
4                2                    -                     -     3      3
...            ...                  ...                   ...   ...    ...
1477           0.5                    -                     -     -      -
1478             -                    -                     -     -      -
1479             -                    -                     -     -      -
1480           2.1                 0.44                  0.44     -      -
1481             -                    -                     -     -      -

     CORSI- Short-handed play Power-play played Power play time  \
0         -                 -                 -               -
1         -                 -                 -               -
2         -                 -                 -               -
3         -                 -                 -               -
4         -                 -                 -               -
...     ...               ...               ...             ...
1477      -                 -                 -           00:15
1478      -                 -                 -           00:45
1479      -                 -                 -           00:11
1480      -                 -                 -           02:08
1481      -                 -                 -           00:23

     Successful power play Short-handed time
0                        -                 -
1                        -                 -
2                        -                 -
3                        -                 -
4                        -                 -
...                    ...               ...
1477                     -                 -
1478                     -                 -
1479                     -                 -
1480                     -                 -
1481                     -                 -

[1482 rows x 18 columns]

In [3]:
lines_new_cleaned.head()

,Line,Plus/Minus,Numbers of shifts,Time on ice,Goals,Opponent's goals,Shots,Shots on goal,Opponent shots total,Shots on goal against,CORSI,CORSI+,CORSI-,Short-handed play,Power-play played,Power play time,Successful power play,Short-handed time
0,"4 K. MacKinnon, 18 A. Wilbur, 6 A. Wilson, 10 ...",-,4.0,01:45,-,-,4,3,-,-,4,4,-,-,-,-,-,-
1,"15 D. Ormiston, 11 S. Potratz, 6 A. Wilson, 12...",-,1.0,00:43,-,-,4,4,-,-,4,4,-,-,-,-,-,-
2,"26 J. Marano, 4 K. MacKinnon, 77 M. Cheesebrou...",-,2.0,00:29,-,-,4,1,-,-,4,4,-,-,-,-,-,-
3,"15 D. Ormiston, 16 L. Scardicchio, 8 A. Bazyle...",-,2.0,00:47,-,-,3,3,-,-,3,3,-,-,-,-,-,-
4,"15 D. Ormiston, 11 S. Potratz, 42 A. Reider, 6...",-,2.0,01:16,-,-,3,2,-,-,3,3,-,-,-,-,-,-

In [ ]:
# output_path = os.path.join(directory, 'lines_new_cleaned.xlsx')
# lines_new_cleaned.to_excel(output_path, index=False)
# print(f"DataFrame exported to {output_path}")

DataFrame exported to /Users/sarahsetiawan/Desktop/CSCAPSTONE/HOCKEYDATA/Instat_NEWDATA/lines_new_cleaned.xlsx

In [5]:
print(lines_new_cleaned.dtypes)

Line                      object
Plus/Minus                object
Numbers of shifts        float64
Time on ice               object
Goals                     object
Opponent's goals          object
Shots                     object
Shots on goal             object
Opponent shots total      object
Shots on goal against     object
CORSI                     object
CORSI+                    object
CORSI-                    object
Short-handed play         object
Power-play played         object
Power play time           object
Successful power play     object
Short-handed time         object
dtype: object

In [9]:
lines_new_cleaned.replace('-', 0, inplace=True)
lines_new_cleaned.head(20)

,Line,Plus/Minus,Numbers of shifts,Time on ice,Goals,Opponent's goals,Shots,Shots on goal,Opponent shots total,Shots on goal against,CORSI,CORSI+,CORSI-,Short-handed play,Power-play played,Power play time,Successful power play,Short-handed time
0,"4 K. MacKinnon, 18 A. Wilbur, 6 A. Wilson, 10 ...",0.0,4.0,01:45,0.0,0.0,4.0,3.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0,0.0,0
1,"15 D. Ormiston, 11 S. Potratz, 6 A. Wilson, 12...",0.0,1.0,00:43,0.0,0.0,4.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0,0.0,0
2,"26 J. Marano, 4 K. MacKinnon, 77 M. Cheesebrou...",0.0,2.0,00:29,0.0,0.0,4.0,1.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0,0.0,0
3,"15 D. Ormiston, 16 L. Scardicchio, 8 A. Bazyle...",0.0,2.0,00:47,0.0,0.0,3.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
4,"15 D. Ormiston, 11 S. Potratz, 42 A. Reider, 6...",0.0,2.0,01:16,0.0,0.0,3.0,2.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
5,"15 D. Ormiston, 4 K. MacKinnon, 42 A. Reider, ...",0.0,1.0,01:00,0.0,0.0,3.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
6,"15 D. Ormiston, 6 A. Wilson, 12 E. Bynan, 10 R...",0.0,1.0,00:45,0.0,0.0,3.0,2.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
7,"19 L. Szczubiala, 6 A. Wilson, 5 C. Kittell, 7...",0.0,1.0,00:24,0.0,0.0,3.0,2.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
8,"47 K. Kratzer, 16 L. Scardicchio, 19 L. Szczub...",0.0,1.0,00:39,0.0,0.0,4.0,2.0,1.0,0.0,3.0,4.0,-1.0,0.0,0.0,0,0.0,0
9,"26 J. Marano, 47 K. Kratzer, 16 L. Scardicchio...",0.0,1.0,00:23,0.0,0.0,3.0,2.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0,0.0,0
10,"47 K. Kratzer, 4 K. MacKinnon, 12 E. Bynan, 77...",0.0,2.0,01:05,0.0,0.0,4.0,2.0,1.0,1.0,3.0,4.0,-1.0,0.0,0.0,0,0.0,0
11,"15 D. Ormiston, 47 K. Kratzer, 77 M. Cheesebro...",0.0,2.5,01:06,0.0,0.0,3.5,1.5,0.5,0.0,3.0,3.5,-0.5,0.0,0.0,0,0.0,0
12,"26 J. Marano, 16 L. Scardicchio, 19 L. Szczubi...",1.0,1.0,00:36,1.0,0.0,2.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
13,"26 J. Marano, 4 K. MacKinnon, 11 S. Potratz, 4...",0.0,14.0,00:56,0.0,0.0,2.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
14,"26 J. Marano, 4 K. MacKinnon, 16 L. Scardicchi...",0.0,8.0,00:43,0.0,0.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
15,"15 D. Ormiston, 11 S. Potratz, 8 A. Bazylewicz...",0.0,1.0,00:55,0.0,0.0,2.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
16,"26 J. Marano, 18 A. Wilbur, 6 A. Wilson, 12 E....",0.0,1.0,00:27,0.0,0.0,2.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
17,"4 K. MacKinnon, 16 L. Scardicchio, 19 L. Szczu...",0.0,1.0,00:32,0.0,0.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
18,"4 K. MacKinnon, 19 L. Szczubiala, 12 E. Bynan,...",0.0,2.0,00:47,0.0,0.0,2.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0
19,"4 K. MacKinnon, 6 A. Wilson, 12 E. Bynan, 13 S...",0.0,2.0,00:32,0.0,0.0,2.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0,0.0,0

In [ ]:
time_columns = ['Time on ice', 'Power play time']
for col in time_columns:
    if col in lines_df.columns:
        lines_df[col] = lines_df[col].replace('0', '00:00')
        # Fill NaN values with '00:00' before splitting
        lines_df[col] = lines_df[col].fillna('00:00')
        # Split the time into minutes and seconds
        lines_df[[f'{col} (mins)', f'{col} (secs)']] = lines_df[col].str.split(':', expand=True)
        # Fill NaN values in the new columns with 0 and convert to integers
        lines_df[f'{col} (mins)'] = lines_df[f'{col} (mins)'].fillna(0).astype(int)
        lines_df[f'{col} (secs)'] = lines_df[f'{col} (secs)'].fillna(0).astype(int)
    else:
        print(f"Column '{col}' not found in DataFrame")

In [11]:
lines_new_cleaned[['Time on ice (Minutes)', 'Time on ice (Seconds)']] = lines_new_cleaned['Time on ice'].str.split(':', expand=True)
lines_new_cleaned.head()

,Line,Plus/Minus,Numbers of shifts,Time on ice,Goals,Opponent's goals,Shots,Shots on goal,Opponent shots total,Shots on goal against,...,CORSI-,Short-handed play,Power-play played,Power play time,Successful power play,Short-handed time,Minutes,Seconds,Time on ice (Minutes),Time on ice (Seconds)
0,"4 K. MacKinnon, 18 A. Wilbur, 6 A. Wilson, 10 ...",0.0,4.0,01:45,0.0,0.0,4.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,01,45,01,45
1,"15 D. Ormiston, 11 S. Potratz, 6 A. Wilson, 12...",0.0,1.0,00:43,0.0,0.0,4.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,00,43,00,43
2,"26 J. Marano, 4 K. MacKinnon, 77 M. Cheesebrou...",0.0,2.0,00:29,0.0,0.0,4.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,00,29,00,29
3,"15 D. Ormiston, 16 L. Scardicchio, 8 A. Bazyle...",0.0,2.0,00:47,0.0,0.0,3.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,00,47,00,47
4,"15 D. Ormiston, 11 S. Potratz, 42 A. Reider, 6...",0.0,2.0,01:16,0.0,0.0,3.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,01,16,01,16